### ISSUE TITLE
docker-worker worker: workerNodeType is required

### ISSUE THREAD

**Issue by milescrabill** [taskcluster/taskcluster-worker-runner#44]
Starting docker-worker via tc-worker-runner without `workerNodeType` configured results in an error like this:

```
TypeError: Cannot read property 'replace' of undefined
    at /home/ubuntu/docker-worker/src/bin/worker.js:169:30
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
    at Function.Module.runMain (module.js:696:11)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

which points us [here](https://github.com/taskcluster/docker-worker/blob/master/src/bin/worker.js#L167-L169).

tc-worker-runner should set this config value for docker-worker, as it is de facto required

**Comment by djmitche** [comment]
@milescrabill I want to say this got solvd?

**Comment by milescrabill** [comment]
I think this was an issue of the config being improperly overwritten, aka my bad.
